'use client'

import ImageUploader from '@/components/admin/ImageUploader'
import { Pencil, Plus, Trash2, X } from 'lucide-react'
import { useCallback, useEffect, useState } from 'react'
import toast from 'react-hot-toast'

const emptyProduct = { name: '', sku: '', price: '', salePrice: '', stock: '0', categoryId: '', status: 'DRAFT', shortDescription: '', description: '', specificationsText: '', images: [], isFeatured: false, isNewArrival: false }
const statuses = ['DRAFT', 'PUBLISHED', 'HIDDEN', 'OUT_OF_STOCK']

export default function AdminProducts() {
  const currency = process.env.NEXT_PUBLIC_CURRENCY_SYMBOL || '$'
  const [products, setProducts] = useState([]); const [categories, setCategories] = useState([]); const [loading, setLoading] = useState(true)
  const [editing, setEditing] = useState(null); const [form, setForm] = useState(emptyProduct); const [saving, setSaving] = useState(false); const [statusFilter, setStatusFilter] = useState('ALL')
  const load = useCallback(async () => { setLoading(true); try { const query = statusFilter === 'ALL' ? '' : `?status=${statusFilter}`; const response = await fetch(`/api/admin/products${query}`, { cache: 'no-store' }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setProducts(data.products || []); setCategories(data.categories || []); setForm((value) => ({ ...value, categoryId: value.categoryId || data.categories?.[0]?.id || '' })) } catch (error) { toast.error(error.message || 'Could not load products') } finally { setLoading(false) } }, [statusFilter])
  useEffect(() => { load() }, [load])
  useEffect(() => { const refresh = () => load(); window.addEventListener('gocart:categories-changed', refresh); return () => window.removeEventListener('gocart:categories-changed', refresh) }, [load])
  const openCreate = () => { setEditing('new'); setForm({ ...emptyProduct, categoryId: categories[0]?.id || '' }) }
  const openEdit = (product) => { setEditing(product.id); setForm({ ...emptyProduct, ...product, price: String(product.price), salePrice: product.salePrice == null ? '' : String(product.salePrice), stock: String(product.stock), images: product.images.map(({ url, publicId }) => ({ url, ...(publicId ? { publicId } : {}) })), specificationsText: Object.entries(product.specifications || {}).map(([key, value]) => `${key}: ${value}`).join('\n') }) }
  const save = async (event) => { event.preventDefault(); if (form.status === 'PUBLISHED' && !form.images.length) return toast.error('Published products need at least one image'); setSaving(true); try { const specifications = {}; form.specificationsText.split('\n').forEach((line) => { const separator = line.indexOf(':'); if (separator > 0) specifications[line.slice(0, separator).trim()] = line.slice(separator + 1).trim() }); const body = { ...form, ...(editing === 'new' ? {} : { id: editing }), salePrice: form.salePrice === '' ? null : form.salePrice, specifications }; delete body.specificationsText; const response = await fetch('/api/admin/products', { method: editing === 'new' ? 'POST' : 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); const data = await response.json(); if (!response.ok) throw new Error(data.details?.fieldErrors ? Object.values(data.details.fieldErrors).flat()[0] : data.error); toast.success(form.status === 'DRAFT' ? 'Product saved as draft' : 'Product published'); setEditing(null); await load(); if (form.status === 'PUBLISHED') window.dispatchEvent(new Event('gocart:catalog-changed')) } catch (error) { toast.error(error.message || 'Could not save product') } finally { setSaving(false) } }
  const remove = async (id) => { if (!confirm('Permanently delete this product and its Cloudinary images?')) return; const response = await fetch(`/api/admin/products?id=${encodeURIComponent(id)}`, { method: 'DELETE' }); const data = await response.json(); if (!response.ok) return toast.error(data.error); toast.success('Product deleted'); load() }
  return <div className='mb-20 max-w-7xl text-slate-700'>
    <div className='mb-6 flex flex-wrap items-end justify-between gap-4'><div><p className='text-sm font-medium text-green-700'>Catalog Management</p><h1 className='text-3xl font-semibold'>Products</h1></div><div className='flex gap-3'><select aria-label='Filter product status' value={statusFilter} onChange={(e) => setStatusFilter(e.target.value)} className='rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm'><option value='ALL'>All statuses</option>{statuses.map((status) => <option key={status}>{status}</option>)}</select><button onClick={openCreate} className='flex items-center gap-2 rounded-xl bg-green-600 px-4 py-2.5 text-sm text-white'><Plus size={18}/> Add Product</button></div></div>
    {editing && <form onSubmit={save} className='mb-8 space-y-5 rounded-xl border border-slate-200 bg-white p-6 shadow-sm'><div className='flex justify-between'><div><h2 className='text-lg font-semibold'>{editing === 'new' ? 'Add New Product' : 'Edit Product'}</h2><p className='text-xs text-slate-500'>Save unfinished work as a draft, then publish when ready.</p></div><button type='button' onClick={() => setEditing(null)}><X/></button></div>
      <div className='grid gap-4 sm:grid-cols-2 lg:grid-cols-3'>{[['name','Product Name','text'],['sku','SKU','text'],['price',`Price (${currency})`,'number'],['salePrice','Sale Price','number'],['stock','Stock','number']].map(([name,label,type]) => <label key={name} className='text-xs font-medium'>{label}<input type={type} min={type === 'number' ? 0 : undefined} step={name === 'price' || name === 'salePrice' ? '.01' : undefined} required={name !== 'salePrice'} value={form[name]} onChange={(e) => setForm({ ...form, [name]: e.target.value })} className='mt-1 w-full rounded-lg border border-slate-200 p-2.5 text-sm'/></label>)}
        <label className='text-xs font-medium'>Category<select required value={form.categoryId} onFocus={async () => { const response = await fetch('/api/admin/categories', { cache: 'no-store' }); if (response.ok) setCategories((await response.json()).categories || []) }} onChange={(e) => setForm({ ...form, categoryId: e.target.value })} className='mt-1 w-full rounded-lg border border-slate-200 p-2.5 text-sm'><option value=''>Select category</option>{categories.map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select></label>
        <label className='text-xs font-medium'>Product Status<select value={form.status} onChange={(e) => setForm({ ...form, status: e.target.value })} className='mt-1 w-full rounded-lg border border-slate-200 p-2.5 text-sm'>{statuses.map((status) => <option key={status}>{status}</option>)}</select></label></div>
      <label className='block text-xs font-medium'>Short Description<textarea maxLength={500} value={form.shortDescription || ''} onChange={(e) => setForm({ ...form, shortDescription: e.target.value })} className='mt-1 min-h-20 w-full rounded-lg border p-2.5 text-sm'/></label>
      <label className='block text-xs font-medium'>Long Description<textarea value={form.description || ''} onChange={(e) => setForm({ ...form, description: e.target.value })} className='mt-1 min-h-32 w-full rounded-lg border p-2.5 text-sm'/></label>
      <label className='block text-xs font-medium'>Specifications <span className='font-normal text-slate-400'>(one “Name: Value” per line)</span><textarea value={form.specificationsText} onChange={(e) => setForm({ ...form, specificationsText: e.target.value })} className='mt-1 min-h-28 w-full rounded-lg border p-2.5 font-mono text-sm'/></label>
      <ImageUploader label='Product gallery' value={form.images} onChange={(images) => setForm({ ...form, images })} multiple maxFiles={12}/>
      <div className='flex gap-6 text-sm'><label><input type='checkbox' checked={form.isNewArrival} onChange={(e) => setForm({ ...form, isNewArrival: e.target.checked })}/> New Arrival</label><label><input type='checkbox' checked={form.isFeatured} onChange={(e) => setForm({ ...form, isFeatured: e.target.checked })}/> Featured</label></div>
      <button disabled={saving} className='rounded-lg bg-slate-800 px-6 py-2.5 text-sm text-white disabled:opacity-60'>{saving ? 'Saving…' : form.status === 'DRAFT' ? 'Save Draft' : 'Save & Publish'}</button>
    </form>}
    <div className='overflow-x-auto rounded-xl border bg-white'><table className='w-full text-left text-sm'><thead className='bg-slate-50'><tr>{['Product','SKU','Price','Stock','Category','Status','Actions'].map((label) => <th key={label} className='px-4 py-3.5'>{label}</th>)}</tr></thead><tbody className='divide-y'>{loading ? <tr><td colSpan='7' className='p-8 text-center'>Loading…</td></tr> : !products.length ? <tr><td colSpan='7' className='p-8 text-center text-slate-500'>No products match this status.</td></tr> : products.map((product) => <tr key={product.id}><td className='px-4 py-3 font-medium'>{product.name}</td><td className='px-4 py-3'>{product.sku}</td><td className='px-4 py-3'>{currency}{Number(product.salePrice ?? product.price).toFixed(2)}</td><td className='px-4 py-3'>{product.stock}</td><td className='px-4 py-3'>{product.category?.name}</td><td className='px-4 py-3'><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${product.status === 'PUBLISHED' ? 'bg-green-100 text-green-700' : product.status === 'DRAFT' ? 'bg-amber-100 text-amber-700' : 'bg-slate-100'}`}>{product.status}</span></td><td className='px-4 py-3'><div className='flex gap-3'><button onClick={() => openEdit(product)} title='Edit'><Pencil size={17}/></button><button onClick={() => remove(product.id)} className='text-red-600' title='Delete'><Trash2 size={17}/></button></div></td></tr>)}</tbody></table></div>
  </div>
}
