'use client'

import ImageUploader from '@/components/admin/ImageUploader'
import { Pencil, Plus, Trash2, X } from 'lucide-react'
import { useEffect, useState } from 'react'
import toast from 'react-hot-toast'

const emptyBanner = { title: 'NEWS', mainHeading: "Gadgets you'll love. Prices you'll trust.", subHeading: 'Free Shipping on Orders Above $50!', description: 'Discover trusted products at prices you will love.', offerText: '20% OFF', secondaryText: 'Best Products', buttonText: 'LEARN MORE', linkUrl: '/shop', position: 0, isActive: true, backgroundImages: [], bannerImages: [] }

export default function AdminBanners() {
  const [banners, setBanners] = useState([]); const [editing, setEditing] = useState(null); const [form, setForm] = useState(emptyBanner); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false)
  const load = async () => { try { const response = await fetch('/api/admin/banners', { cache: 'no-store' }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setBanners(data.banners || []) } catch (error) { toast.error(error.message || 'Could not load hero banners') } finally { setLoading(false) } }
  useEffect(() => { load() }, [])
  const openCreate = () => { setEditing('new'); setForm(emptyBanner) }
  const openEdit = (banner) => { setEditing(banner.id); setForm({ ...emptyBanner, ...banner, backgroundImages: [{ url: banner.imageUrl, publicId: banner.imagePublicId }], bannerImages: banner.mobileImageUrl ? [{ url: banner.mobileImageUrl, publicId: banner.mobileImagePublicId }] : [] }) }
  const save = async (event) => { event.preventDefault(); if (!form.backgroundImages[0]) return toast.error('Background image is required'); setSaving(true); try { const background = form.backgroundImages[0]; const artwork = form.bannerImages[0]; const body = { ...form, ...(editing === 'new' ? {} : { id: editing }), imageUrl: background.url, imagePublicId: background.publicId, mobileImageUrl: artwork?.url || null, mobileImagePublicId: artwork?.publicId || null, position: Number(form.position) }; delete body.backgroundImages; delete body.bannerImages; const response = await fetch('/api/admin/banners', { method: editing === 'new' ? 'POST' : 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); const data = await response.json(); if (!response.ok) throw new Error(data.details?.fieldErrors ? Object.values(data.details.fieldErrors).flat()[0] : data.error); toast.success('Hero banner saved'); setEditing(null); await load(); window.dispatchEvent(new Event('gocart:hero-changed')) } catch (error) { toast.error(error.message || 'Could not save hero banner') } finally { setSaving(false) } }
  const remove = async (id) => { if (!confirm('Delete this hero banner and its images?')) return; const response = await fetch(`/api/admin/banners?id=${encodeURIComponent(id)}`, { method: 'DELETE' }); const data = await response.json(); if (!response.ok) return toast.error(data.error); setBanners((items) => items.filter((item) => item.id !== id)); toast.success('Hero banner deleted') }
  return <div className='mb-20 max-w-7xl text-slate-700'>
    <div className='mb-6 flex items-end justify-between'><div><p className='text-sm font-medium text-green-700'>Landing Page CMS</p><h1 className='text-3xl font-semibold'>Hero Banners</h1></div><button onClick={openCreate} className='flex items-center gap-2 rounded-xl bg-green-600 px-4 py-2.5 text-sm text-white'><Plus size={18}/> Add Hero Banner</button></div>
    {editing && <form onSubmit={save} className='mb-8 space-y-5 rounded-xl border bg-white p-6 shadow-sm'><div className='flex justify-between'><div><h2 className='font-semibold'>{editing === 'new' ? 'Create Hero Banner' : 'Edit Hero Banner'}</h2><p className='text-xs text-slate-500'>All content below is stored in the database and shown by display order.</p></div><button type='button' onClick={() => setEditing(null)}><X/></button></div>
      <div className='grid gap-5 lg:grid-cols-2'><ImageUploader label='Background image' required aspect='landscape' value={form.backgroundImages} onChange={(backgroundImages) => setForm({ ...form, backgroundImages })}/><ImageUploader label='Banner/product artwork (optional)' value={form.bannerImages} onChange={(bannerImages) => setForm({ ...form, bannerImages })}/></div>
      <div className='grid gap-4 sm:grid-cols-2 lg:grid-cols-3'>{[['title','Badge / NEWS'],['mainHeading','Main Heading'],['subHeading','Sub Heading'],['offerText','Offer Text'],['secondaryText','Secondary Text'],['buttonText','Button Text'],['linkUrl','Button URL'],['position','Display Order']].map(([name,label]) => <label key={name} className='text-xs font-medium'>{label}<input required value={form[name] ?? ''} type={name === 'position' ? 'number' : 'text'} min={name === 'position' ? 0 : undefined} onChange={(e) => setForm({ ...form, [name]: e.target.value })} className='mt-1 w-full rounded-lg border p-2.5 text-sm'/></label>)}</div>
      <label className='block text-xs font-medium'>Description<textarea required maxLength={1000} value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} className='mt-1 min-h-24 w-full rounded-lg border p-2.5 text-sm'/></label>
      <label className='flex items-center gap-2 text-sm'><input type='checkbox' checked={form.isActive} onChange={(e) => setForm({ ...form, isActive: e.target.checked })}/> Visible on storefront</label>
      <button disabled={saving} className='rounded-lg bg-slate-800 px-6 py-2.5 text-sm text-white disabled:opacity-60'>{saving ? 'Saving…' : 'Save Hero Banner'}</button>
    </form>}
    <div className='overflow-x-auto rounded-xl border bg-white'><table className='w-full text-left text-sm'><thead className='bg-slate-50'><tr>{['Order','Preview','Heading','Offer / Secondary','Visibility','Actions'].map((label) => <th key={label} className='px-4 py-3.5'>{label}</th>)}</tr></thead><tbody className='divide-y'>{loading ? <tr><td colSpan='6' className='p-8 text-center'>Loading…</td></tr> : !banners.length ? <tr><td colSpan='6' className='p-8 text-center text-slate-500'>No CMS hero banners yet. The storefront uses safe fallback content until one is created.</td></tr> : banners.map((banner) => <tr key={banner.id}><td className='px-4 py-3'>{banner.position}</td><td className='px-4 py-3'><img src={banner.imageUrl} alt='' className='h-14 w-24 rounded object-cover'/></td><td className='px-4 py-3'><p className='font-medium'>{banner.mainHeading}</p><p className='text-xs text-slate-500'>{banner.subHeading}</p></td><td className='px-4 py-3'>{banner.offerText} / {banner.secondaryText}</td><td className='px-4 py-3'>{banner.isActive ? 'Visible' : 'Hidden'}</td><td className='px-4 py-3'><div className='flex gap-3'><button onClick={() => openEdit(banner)}><Pencil size={17}/></button><button onClick={() => remove(banner.id)} className='text-red-600'><Trash2 size={17}/></button></div></td></tr>)}</tbody></table></div>
  </div>
}
