'use client'

import { useEffect, useState } from 'react'
import toast from 'react-hot-toast'
import { Trash2 } from 'lucide-react'

const initial = { code: '', description: '', type: 'PERCENTAGE', amount: '', usageLimit: '', startsAt: new Date().toISOString().slice(0, 10), expiresAt: '', isActive: true }

export default function AdminCoupons() {
  const [coupons, setCoupons] = useState([]); const [form, setForm] = useState(initial); const [loading, setLoading] = useState(true)
  const load = async () => { setLoading(true); const response = await fetch('/api/admin/coupons', { cache: 'no-store' }); const data = await response.json(); if (response.ok) setCoupons(data.coupons || []); else toast.error(data.error); setLoading(false) }
  useEffect(() => { load() }, [])
  const create = async (event) => { event.preventDefault(); const response = await fetch('/api/admin/coupons', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ...form, usageLimit: form.usageLimit ? Number(form.usageLimit) : null, expiresAt: form.expiresAt || null }) }); const data = await response.json(); if (!response.ok) return toast.error(data.details?.fieldErrors ? Object.values(data.details.fieldErrors).flat()[0] : data.error); toast.success('Coupon created'); setForm(initial); load() }
  const toggle = async (coupon) => { const response = await fetch('/api/admin/coupons', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ id: coupon.id, isActive: !coupon.isActive }) }); response.ok ? (toast.success('Coupon updated'), load()) : toast.error('Could not update coupon') }
  const remove = async (id) => { if (!confirm('Permanently delete this unused coupon?')) return; const response = await fetch(`/api/admin/coupons?id=${encodeURIComponent(id)}`, { method: 'DELETE' }); const data = await response.json(); response.ok ? (toast.success('Coupon deleted'), load()) : toast.error(data.error) }
  return <div className='text-slate-700 max-w-6xl mb-20'><div className='mb-6'><p className='text-sm font-medium text-green-700'>Promotions</p><h1 className='text-3xl font-semibold'>Coupons</h1></div>
    <form onSubmit={create} className='bg-white p-6 rounded-xl border border-slate-200 grid sm:grid-cols-2 lg:grid-cols-3 gap-4 mb-8'>{[['code','Code','text'],['description','Description','text'],['amount','Amount','number'],['usageLimit','Usage limit','number'],['startsAt','Starts','date'],['expiresAt','Expires','date']].map(([name,label,type]) => <label key={name} className='text-xs font-medium'>{label}<input type={type} min={type === 'number' ? 1 : undefined} step={name === 'amount' ? '0.01' : undefined} required={['code','amount','startsAt'].includes(name)} value={form[name]} onChange={(e) => setForm({ ...form, [name]: e.target.value })} className='mt-1 w-full p-2.5 border border-slate-200 rounded-lg text-sm' /></label>)}<label className='text-xs font-medium'>Discount type<select value={form.type} onChange={(e) => setForm({ ...form, type: e.target.value })} className='mt-1 w-full p-2.5 border border-slate-200 rounded-lg text-sm'><option value='PERCENTAGE'>Percentage</option><option value='FIXED'>Fixed amount</option></select></label><div className='flex items-end'><button className='w-full p-2.5 bg-slate-800 text-white rounded-lg text-sm'>Add Coupon</button></div></form>
    <div className='bg-white rounded-xl border border-slate-200 overflow-x-auto'><table className='w-full text-sm text-left'><thead className='bg-slate-50'><tr>{['Code','Discount','Validity','Usage','Status','Actions'].map((label) => <th key={label} className='p-4'>{label}</th>)}</tr></thead><tbody className='divide-y'>{loading ? <tr><td colSpan='6' className='p-8 text-center'>Loading...</td></tr> : coupons.map((coupon) => <tr key={coupon.id}><td className='p-4 font-semibold'>{coupon.code}</td><td className='p-4'>{coupon.type === 'PERCENTAGE' ? `${Number(coupon.amount)}%` : Number(coupon.amount).toFixed(2)}</td><td className='p-4'>{new Date(coupon.startsAt).toLocaleDateString()} – {coupon.expiresAt ? new Date(coupon.expiresAt).toLocaleDateString() : 'No expiry'}</td><td className='p-4'>{coupon.usedCount}{coupon.usageLimit ? ` / ${coupon.usageLimit}` : ''}</td><td className='p-4'><button onClick={() => toggle(coupon)} className={`px-3 py-1 rounded-full ${coupon.isActive ? 'bg-green-100 text-green-800' : 'bg-slate-100'}`}>{coupon.isActive ? 'Active' : 'Inactive'}</button></td><td className='p-4'><button onClick={() => remove(coupon.id)} className='text-red-600'><Trash2 size={17} /></button></td></tr>)}</tbody></table></div>
  </div>
}
